### ISSUE TITLE
No module named 'src'

### ISSUE THREAD

**Issue by yilinxia** [dodaro/cnl2asp#1]
Hi there,

We are trying to run the code but encounter the issue below, could you please take a look at it?
```
python 3.10.6
lark 1.1.2
```

```
(python310) Yilins-MacBook-Pro-2:cnl2asp yilinxia$ python3.10 src/main.py src/examples/3Col 3Col.lp
Traceback (most recent call last):
  File "/Users/yilinxia/cnl2asp/src/main.py", line 3, in <module>
    from cnl.compile import CNLFile, CNLCompiler, DefinitionError
  File "/Users/yilinxia/cnl2asp/src/cnl/compile.py", line 10, in <module>
    from src.cnl.parse import *
ModuleNotFoundError: No module named 'src'
```

**Comment by dodaro** [comment]
Thanks! It was a bug with an import. It should be fixed now.
